---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: 'strimzi'
  name: 'strimzi'
spec:
  image: 'quay.io/openshift/origin-prometheus:4.7'
  containers:
  - args:
    - -provider=openshift
    - -https-address=:9091
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9090
    - -openshift-service-account=prometheus-service-account
    - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb":"get"}}'
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret-file=/etc/proxy/secrets/session_secret
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - -skip-auth-regex=^/metrics
    image: 'quay.io/openshift/origin-oauth-proxy:4.7'
    name: prometheus-proxy
    ports:
    - containerPort: 9091
      name: oproxy
    resources: {}
    volumeMounts:
    - mountPath: /etc/tls/private
      name: 'secret-prometheus-k8s-tls'
    - mountPath: /etc/proxy/secrets
      name: 'secret-prometheus-k8s-proxy'
  externalUrl: 'https://prometheus-route-game-kafka.apps.ocp4.mrsunshine.be'
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 1
  resources:
    requests:
      cpu: '100m'
      memory: '400Mi'
    limits:
      cpu: '500m'
      memory: '1Gi' 
  retention: '5d'
  ruleNamespaceSelector: {}
  ruleSelector: {}
  secrets:
  - 'prometheus-k8s-tls'
  - 'prometheus-k8s-proxy'
  serviceAccountName: prometheus-service-account
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: '10Gi'